### ISSUE TITLE
Upgrade Issue during systemd steps

### ISSUE THREAD

**Issue by LoXan007** [YunoHost-Apps/peertube_ynh#346]
### Describe the bug

Hi,
recently i upgraded my Peertube instance from 4.2.2~ynh3 to 4.2.3~yhn1 and i notice a (for me strange bug). I started the upgrade as always via the yunohost admin web interface and the upgrade process ran without problems until the step "Starting a systemd service". 
Normally the mentioned step is a thing from a few seconds but this time i waited over 20 minutes and nothing happened at this step.

So i made a reboot of my server because the yunohost admin web interface was broken somehow, too. Then i typed the url of my instance into the browser because i wanted to be sure that my instance still works. Luckily it was still the case. 
Interestingly the version of my instance is now 4.3.0 whether the upgrade process of yunohost didn't run through and yunohost thinks that Peertube is installed in version 4.2.2~ynh3 (which is obvious wrong). The login tinto the yunohost admin interface works again too.

For me it seems that the upgrade process of the app itself ran through but somehow yunohost triggered a bug with systemd.

Now i'm hoping for help because i don't want to force a server reboot everytime if i update my Peertube instance.

### Context

- Hardware: *Dedicated Root Server (Debian 11 with newest updates)
- YunoHost version: 11.0.9.14
- I have access to my server: Through SSH | through the webadmin 
- Are you in a special context or did you perform some particular tweaking on your YunoHost instance?: no 

### Logs
Link to Log:
https://paste.yunohost.org/raw/isudoqolux

Best regards
LoXan007

**Comment by yalh76** [comment]
We have increased the service start during upgrade => https://github.com/YunoHost-Apps/peertube_ynh/pull/339 because during the service start, it upgrades the database ...
Maybe 5400s=1H30 is too much but you have to look the content of `/var/log/peertube/peertube.log` during upgrade to check whats happened, another option is to just restart peertube service if the database upgrade is complete

**Comment by LoXan007** [comment]
Hi, 

i tried it again and after very much waiting i got a gateway error from nginx and the upgrade process stops. Plus the yunohost admin interface is frozen again so i guess i need to restart the server again to get a functional yunohost admin interface back.

To get the log you mentioned i sign into my server via ssh and the username admin but my server said that he couldn't the log. If i try it with the commands "nano var/log/peertube/peertube.log" and "cd var/log/peertube"  my server says the directory/file don't exist.
Sry if i oversee something important but i'm not so familiar with command-lines on servers. I'm prefering GUIs:)

So can you reopen the issue? And do can you have idea why the update process stops with a nginx error?

Thanks in advance
LoXan007

**Comment by LoXan007** [comment]
Hi,

me again. I don't how but my problem is fixed. A while after the nginx error i try to sign again in yunohost via the admin interface and  the login is working now (without server restart).
And yunohost shows the correct version of peertube now, too.

So everything is ok now:)

Best regards
LoXan007

**Comment by yalh76** [comment]
> Hi,
> 
> i tried it again and after very much waiting i got a gateway error from nginx and the upgrade process stops. Plus the yunohost admin interface is frozen again so i guess i need to restart the server again to get a functional yunohost admin interface back.
> 
> To get the log you mentioned i sign into my server via ssh and the username admin but my server said that he couldn't the log. If i try it with the commands "nano var/log/peertube/peertube.log" and "cd var/log/peertube" my server says the directory/file don't exist. Sry if i oversee something important but i'm not so familiar with command-lines on servers. I'm prefering GUIs:)
> 
> So can you reopen the issue? And do can you have idea why the update process stops with a nginx error?
> 
> Thanks in advance LoXan007

it because you need to do: `nano /var/log/peertube/peertube.log` you forgot the starting `/`
